### ISSUE TITLE
Add section in oxd docs for "plugins"

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/docs-oxd#1]
Similar to how we have articles and reference in our Gluu Server docs, lets add a section in these docs called "plugins."

The first plugin we can document is WordPress. The second is Magento.

**Comment by zamilskhan** [comment]
Added:
https://github.com/GluuFederation/docs-oxd/blob/master/sources/plugin/index.md

**Comment by yuriyz** [comment]
@zamilskhan I'm going to re-organize oxd docs a bit (as part of #2 ). Please pull changes each time before push to avoid merge conflicts.
