### ISSUE TITLE
Update Protocol page for all registration options

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/docs-oxd#12]
This [Protocol page](https://oxd.gluu.org/docs/oxdserver/#register-site) should describe all registration configuration parameters, whether they are required or optional, default values, and what they are used for.

**Comment by yuriyz** [comment]
need to check all operations

**Comment by yuriyz** [comment]
@nynymike done in https://github.com/GluuFederation/docs-oxd/commit/2d1fab4bedcfab459bc683c7c352f31ed7b8a420
